### PR TITLE
dsviz_write function uses webshot to save a png of the htmlwidget; webshot need phantomjs, thus, webshot's installing function included

### PR DESCRIPTION
**Pull request by brazadas**

### CODE REVIEW

**Comment by jpmarindiaz** [comment]
Is there a way to install phantomjs only if it is not installed? It makes no sense to install things every time the function is run

**Comment by brazadas** [comment]
well... yes there is a function, a webshot's function that tells you if it is or not installed; I will then include the installation only if it is not installed, is it right?

**Comment by brazadas** [comment]
@jpmarindiaz

**Comment by jpmarindiaz** [comment]
yes

**Pull request merged**
